package com.example.panels

import okhttp3.Cookie
import okhttp3.CookieJar
import okhttp3.FormBody
import okhttp3.HttpUrl
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.io.IOException
import java.util.concurrent.TimeUnit

class XuiApiException(message: String, val httpCode: Int = 0, cause: Throwable? = null) :
    IOException(message, cause)

/** Result of a successful inbound creation. */
data class XuiCreatedInbound(
    val id: Int,
    val port: Int,
    val raw: JSONObject
)

/**
 * Minimal, defensive 3X-UI HTTP API client.
 *
 * It works with panels that are reachable over plain HTTP (the installer's default when no
 * certificate is configured) as well as HTTPS, and it tolerates the differences between panel
 * releases:
 *  - authentication: the API token (Bearer) is tried first; when the panel hides the API behind
 *    a 401/403/404 the client transparently logs in with the generated username/password and
 *    re-uses the session cookie;
 *  - inbound payloads: nested JSON objects are tried first and the legacy stringified form is used
 *    as a fallback when the panel rejects them.
 *
 * Nothing here talks to Android APIs so it can be unit-tested on the JVM.
 */
class XuiApiClient(
    panelUrl: String,
    private val apiToken: String = "",
    private val username: String = "",
    private val password: String = "",
    httpClient: OkHttpClient? = null,
    /** SHA-256 of the panel's self-signed certificate (recorded at install time), if it has one. */
    pinnedCertSha256: String = ""
) {
    val baseUrl: String = normalizeBase(panelUrl)

    private val cookieJar = MemoryCookieJar()
    private val http: OkHttpClient = (httpClient ?: defaultClient())
        .let { if (pinnedCertSha256.isNotBlank() && baseUrl.startsWith("https://")) PinnedTls.client(it, pinnedCertSha256) else it }
        .newBuilder()
        .cookieJar(cookieJar)
        .followRedirects(false)
        .followSslRedirects(false)
        .build()

    private var sessionReady = false
    private val jsonType = "application/json; charset=utf-8".toMediaType()

    // ---- high level calls ---------------------------------------------------------------------

    /** Throws when neither the token nor the credentials give access to the API. */
    fun requireAccess() {
        val res = request("GET", "/panel/api/inbounds/list")
        if (!res.optBoolean("success", false)) {
            throw XuiApiException(res.optString("msg").ifBlank { "3X-UI API rejected the request" })
        }
    }

    fun listInbounds(): JSONArray {
        val res = request("GET", "/panel/api/inbounds/list")
        check(res.optBoolean("success", false)) { res.optString("msg").ifBlank { "Cannot list inbounds" } }
        return res.optJSONArray("obj") ?: JSONArray()
    }

    fun usedPorts(): Set<Int> {
        val list = listInbounds()
        return (0 until list.length()).mapNotNull { list.optJSONObject(it)?.optInt("port")?.takeIf { p -> p > 0 } }.toSet()
    }

    /** Returns (privateKey, publicKey) generated by the panel itself. */
    fun newX25519(): Pair<String, String> {
        val res = request("GET", "/panel/api/server/getNewX25519Cert")
        val obj = res.optJSONObject("obj")
            ?: throw XuiApiException("3X-UI did not return a Reality key pair")
        val priv = obj.optString("privateKey")
        val pub = obj.optString("publicKey")
        if (priv.isBlank() || pub.isBlank()) throw XuiApiException("3X-UI returned an empty Reality key pair")
        return priv to pub
    }

    /**
     * Creates the inbound. [settings], [streamSettings] and [sniffing] are plain JSON objects; they
     * are converted to whatever representation the panel accepts.
     */
    fun addInbound(
        remark: String,
        port: Int,
        protocol: String,
        settings: JSONObject,
        streamSettings: JSONObject,
        sniffing: JSONObject
    ): XuiCreatedInbound {
        fun payload(nested: Boolean) = JSONObject()
            .put("remark", remark)
            .put("enable", true)
            .put("listen", "")
            .put("port", port)
            .put("protocol", protocol)
            .put("expiryTime", 0)
            .put("total", 0)
            .put("up", 0)
            .put("down", 0)
            .put("settings", if (nested) settings else settings.toString())
            .put("streamSettings", if (nested) streamSettings else streamSettings.toString())
            .put("sniffing", if (nested) sniffing else sniffing.toString())

        var firstError: String? = null
        for (nested in listOf(true, false)) {
            val res = try {
                request("POST", "/panel/api/inbounds/add", payload(nested))
            } catch (e: XuiApiException) {
                // HTTP 400 style bind errors are what a panel returns for a payload shape it does
                // not accept; try the other representation. Anything else (network, auth) is fatal.
                if (e.httpCode == 400 || e.httpCode == 422) {
                    if (firstError == null) firstError = e.message
                    continue
                }
                throw e
            }
            if (res.optBoolean("success", false)) {
                val obj = res.optJSONObject("obj") ?: JSONObject()
                return XuiCreatedInbound(obj.optInt("id", -1), port, obj)
            }
            val msg = res.optString("msg").ifBlank { "3X-UI rejected the inbound" }
            if (firstError == null) firstError = msg
            // A port clash or a duplicate remark will not be fixed by switching payload shape.
            if (msg.contains("port", true) && msg.contains("exist", true)) break
            if (msg.contains("duplicate", true) || msg.contains("already", true)) break
        }
        throw XuiApiException(firstError ?: "3X-UI rejected the inbound")
    }

    /** Looks the inbound up again from the panel database; null when it is not there. */
    fun readBack(port: Int): JSONObject? {
        val list = listInbounds()
        for (i in 0 until list.length()) {
            val o = list.optJSONObject(i) ?: continue
            if (o.optInt("port") == port) return o
        }
        return null
    }

    fun deleteInbound(id: Int) {
        if (id <= 0) return
        runCatching { request("POST", "/panel/api/inbounds/del/$id", JSONObject()) }
    }

    /** Certificate/key paths the panel itself serves HTTPS with, or null when it has none. */
    fun panelCertificate(): Pair<String, String>? = runCatching {
        val res = request("POST", "/panel/setting/all", JSONObject())
        val obj = res.optJSONObject("obj") ?: return@runCatching null
        val cert = obj.optString("webCertFile")
        val key = obj.optString("webKeyFile")
        if (cert.isNotBlank() && key.isNotBlank()) cert to key else null
    }.getOrNull()

    /** All share links currently exported by the panel (best effort). */
    fun allLinks(): List<String> = runCatching {
        val res = request("GET", "/panel/api/inbounds/allLinks")
        val arr = res.optJSONArray("obj") ?: JSONArray()
        (0 until arr.length()).map { arr.optString(it) }
    }.getOrDefault(emptyList())

    // ---- transport ----------------------------------------------------------------------------

    private fun request(method: String, path: String, body: JSONObject? = null): JSONObject {
        val authAttempts = buildList {
            if (apiToken.isNotBlank()) add("token")
            if (username.isNotBlank() && password.isNotBlank()) add("session")
        }
        if (authAttempts.isEmpty()) throw XuiApiException("No API token or login credentials for this panel")

        var lastFailure: XuiApiException? = null
        for (mode in authAttempts) {
            try {
                if (mode == "session") ensureSession()
                val res = execute(method, path, body, bearer = mode == "token")
                return res
            } catch (e: XuiApiException) {
                // 401/403/404 on an authenticated route means "not logged in / token not accepted".
                if (e.httpCode == 401 || e.httpCode == 403 || e.httpCode == 404) {
                    lastFailure = e
                    if (mode == "session") sessionReady = false
                    continue
                }
                throw e
            }
        }
        throw XuiApiException(
            "The panel did not accept the saved API token or login (HTTP ${lastFailure?.httpCode ?: 0}). " +
                "Open the panel once in the browser to confirm the credentials.",
            lastFailure?.httpCode ?: 0
        )
    }

    private fun ensureSession() {
        if (sessionReady) return
        val form = FormBody.Builder().add("username", username).add("password", password).build()
        val req = Request.Builder().url(url("/login")).post(form).build()
        try {
            http.newCall(req).execute().use { resp ->
                val text = resp.body?.string().orEmpty()
                if (resp.code in 300..399) throw XuiApiException("Unexpected redirect while logging in", resp.code)
                if (!resp.isSuccessful) throw XuiApiException("Panel login failed (HTTP ${resp.code})", resp.code)
                val json = runCatching { JSONObject(text) }.getOrNull()
                    ?: throw XuiApiException("Panel login returned an unreadable response", resp.code)
                if (!json.optBoolean("success", false)) {
                    throw XuiApiException(json.optString("msg").ifBlank { "Panel login rejected the credentials" }, 401)
                }
                sessionReady = true
            }
        } catch (e: XuiApiException) {
            throw e
        } catch (e: IOException) {
            throw transportFailure(e)
        }
    }

    private fun transportFailure(e: IOException): XuiApiException = when {
        e is java.net.UnknownServiceException && e.message.orEmpty().contains("CLEARTEXT", ignoreCase = true) ->
            XuiApiException(
                "Android blocks plain-HTTP panels. Install the panel again from this app (it enables a " +
                    "pinned HTTPS certificate) or turn on HTTPS in 3X-UI.",
                cause = e
            )
        e is javax.net.ssl.SSLException && e.message.orEmpty().contains("pinned", ignoreCase = true) ->
            XuiApiException("The panel presented a different certificate than the one recorded at install time.", cause = e)
        e is javax.net.ssl.SSLException && isPlainHttpReply(e) ->
            XuiApiException(
                "The panel answers over plain HTTP, so HTTPS was not enabled on it. Tap Retry Installation " +
                    "and enter the SSH details again: it keeps the existing panel and only repairs HTTPS.",
                cause = e
            )
        e is java.net.ConnectException || e is java.net.SocketTimeoutException || e is java.net.NoRouteToHostException ->
            XuiApiException(
                "Cannot reach the panel port from this device (${e.message}). Open it in the VPS/cloud firewall.",
                cause = e
            )
        else -> XuiApiException("Cannot reach the panel: ${e.message}", cause = e)
    }

    /** A TLS client talking to a plain-HTTP server fails with one of these messages. */
    private fun isPlainHttpReply(e: Throwable): Boolean {
        val text = generateSequence(e) { it.cause }.joinToString(" ") { it.message.orEmpty() }
        return listOf("TLS packet header", "plaintext connection", "Unrecognized SSL message", "not an SSL/TLS record")
            .any { text.contains(it, ignoreCase = true) }
    }

    private fun execute(method: String, path: String, body: JSONObject?, bearer: Boolean): JSONObject {
        val builder = Request.Builder().url(url(path)).header("Accept", "application/json")
        if (bearer) builder.header("Authorization", "Bearer $apiToken")
        if (method == "GET") builder.get()
        else builder.post((body ?: JSONObject()).toString().toRequestBody(jsonType))
        try {
            http.newCall(builder.build()).execute().use { resp ->
                val text = resp.body?.string().orEmpty()
                if (resp.code in 300..399) throw XuiApiException("Redirected (HTTP ${resp.code})", 401)
                if (!resp.isSuccessful) {
                    val msg = runCatching { JSONObject(text).optString("msg") }.getOrNull().orEmpty()
                    throw XuiApiException(msg.ifBlank { "3X-UI HTTP ${resp.code}" }, resp.code)
                }
                return runCatching { JSONObject(text) }.getOrElse {
                    // An HTML login page means the request was not authenticated.
                    throw XuiApiException("Panel answered with a non-API page", 401)
                }
            }
        } catch (e: XuiApiException) {
            throw e
        } catch (e: IOException) {
            throw transportFailure(e)
        }
    }

    private fun url(path: String): HttpUrl =
        (baseUrl + path).toHttpUrlOrNull() ?: throw XuiApiException("Invalid panel address: $baseUrl")

    private class MemoryCookieJar : CookieJar {
        private val store = mutableListOf<Cookie>()
        @Synchronized
        override fun saveFromResponse(url: HttpUrl, cookies: List<Cookie>) {
            cookies.forEach { c -> store.removeAll { it.name == c.name && it.domain == c.domain && it.path == c.path } }
            store.addAll(cookies)
        }
        @Synchronized
        override fun loadForRequest(url: HttpUrl): List<Cookie> =
            store.filter { it.matches(url) }
    }

    companion object {
        /**
         * Panel URL without trailing slash and without a trailing "/panel" page segment, so
         * "http://1.2.3.4:2053/abcd/panel/" and "http://1.2.3.4:2053/abcd/" both become
         * "http://1.2.3.4:2053/abcd".
         */
        fun normalizeBase(panelUrl: String): String {
            var s = panelUrl.trim().substringBefore('?').substringBefore('#').trimEnd('/')
            if (s.endsWith("/panel")) s = s.removeSuffix("/panel").trimEnd('/')
            return s
        }

        private fun defaultClient() = OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .readTimeout(25, TimeUnit.SECONDS)
            .writeTimeout(25, TimeUnit.SECONDS)
            .build()
    }
}
